name: "Build"

# on: 
#   push:
#     branches: 
#       - main
#     paths-ignore:
#       - '**/*.md'
#       - '**/*.gitignore'
#       - '**/*.gitattributes'
  
#   workflow_dispatch:
#     branches:
#       - main
#     paths-ignore:
#       - '**/*.md'
#       - '**/*.gitignore'
#       - '**/*.gitattributes'

on: 
  push:
  schedule:
    - cron: '0/5 * * * *'  # every day at midnight

jobs:
  increase-browser-version:
    runs-on: linux-vm
    steps:
      - name: checkout master
        uses: actions/checkout@v3
        with:
          ref: 'master'
      
      - name: reset working space
        run: |
          git restore *
          git reset
          
      - name: pull new source
        run: git pull

      - name: update version
        shell: bash
        id: update_version
        run: |
          file_path="package.json"
          version=$(jq -r '.version' $file_path)

          IFS='.' read -ra version_parts <<< "$version"
          last_part=${version_parts[3]}

          new_last_part=$((last_part+1))

          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}.$new_last_part"
          jq --arg new_version "$new_version" '.version = $new_version' $file_path > tmp.json && mv tmp.json $file_path

          echo "::set-output name=new_version::$new_version"
      
      - name: updated to version ${{steps.update_version.outputs.new_version}}
        run: echo ${{steps.update_version.outputs.new_version}}

      - name: show change
        run: git status
      # - name: commit change
      #   uses: devops-infra/action-commit-push@master
      #   with:
      #     github_token: "${{ secrets.GITHUB_TOKEN }}"
      #     add_timestamp: true
      #     commit_prefix: "[AUTO]"
      #     commit_message: ${{ env.version }}
      #     force: false
      #     target_branch: master

  increase-core-version:
    runs-on: linux-vm
    steps:
      - name: checkout master
        uses: actions/checkout@v3
        with:
          repository: 'nguyenphl/brave-core'
          ref: 'master'

      - name: reset working space
        run: |
          git restore *
          git reset
      
      - name: pull new source
        run: git pull

      - name: get current version
        run: ls ../

      - name: update version
        id: update_version
        shell: bash
        run: |
          file_path="package.json"
          version=$(jq -r '.version' $file_path)

          IFS='.' read -ra version_parts <<< "$version"
          last_part=${version_parts[3]}

          new_last_part=$((last_part+1))

          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}.$new_last_part"
          jq --arg new_version "$new_version" '.version = $new_version' $file_path > tmp.json && mv tmp.json $file_path

          echo "::set-output name=new_version::$new_version"

      - name: updated to version ${{steps.update_version.outputs.new_version}}
        run: echo ${{steps.update_version.outputs.new_version}}

      - name: change chromium version
        run: |
          # Read the current patch version from the patch file
          patch=$(grep "^+PATCH=" ./patches/chrome-VERSION.patch | cut -d "=" -f 2)

          # Convert the patch version to an integer
          patch=$(($patch))

          # Increment the patch version by 1
          patch=$(($patch + 1))

          # Replace the old patch version with the new one
          sed -i "s/^+PATCH=[0-9]*/+PATCH=$patch/" ./patches/chrome-VERSION.patch
        
      - name: show change
        run: git status

      

  # build:
  #   strategy:
  #     # os: []
  #     # arch: []
  #     matrix:
  #       include:
  #         # - os: windows-vm
  #         #   arch: ia32
  #         # - os: windows-vm
  #         #   arch: x64
  #         - os: linux-vm
  #           arch: amd64
  #         # - os: linux-vm
  #         #   arch: arm64
  #         # - os: android-vm
  #         #   arch: arm
        
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: checkout master
  #       uses: actions/checkout@v3
  #       with:
  #         ref: 'master'

  #     - name: pull new source
  #       run: git pull

  #     - name: install deps
  #       run: npm i

  #     - name: init
  #       run: npm run init --target_arch=${{ matrix.arch }}

  #     - name: build
  #       run: npm run build Release --target_arch=${{ matrix.arch }}

  # test:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:

  # create_dist:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
