name: "Build"

# on: 
#   push:
#     branches: 
#       - main
#     paths-ignore:
#       - '**/*.md'
#       - '**/*.gitignore'
#       - '**/*.gitattributes'
  
#   workflow_dispatch:
#     branches:
#       - main
#     paths-ignore:
#       - '**/*.md'
#       - '**/*.gitignore'
#       - '**/*.gitattributes'

on: 
  push:
  schedule:
    - cron: '*/1 * * * *' 

jobs:
  increase-browser-version:
    runs-on: linux-vm
    steps:
      - name: checkout master
        uses: actions/checkout@v3
        with:
          ref: 'master'
      
      - name: reset working space
        run: |
          git restore *
          git reset
          
      - name: pull new source
        run: git pull

      - name: update version
        shell: bash
        id: update_version
        run: |
          file_path="package.json"
          version=$(jq -r '.version' $file_path)

          IFS='.' read -ra version_parts <<< "$version"
          last_part=${version_parts[2]}

          new_last_part=$((last_part+1))

          new_version="${version_parts[0]}.${version_parts[1]}.$new_last_part"
          jq --arg new_version "$new_version" '.version = $new_version' $file_path > tmp.json && mv tmp.json $file_path

          echo "new_version=$new_version" >> $GITHUB_ENV
      
      - name: updated to version ${{env.new_version}}
        run: echo ${{env.new_version}}

      - name: show change
        run: git status

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: herond-builds@herondlabs.org
          author_name: herond-builds
          message: ${{env.new_version}}
          branch: master
      # - name: commit change
      #   run: |
      #     git config user.email "herond-builds@herondlabs.com"
      #     git config user.name "herond-builds"
      #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      #     git add package.json
      #     git commit -m ${{env.new_version}}
      #     git push
      # - name: commit change
      #   uses: devops-infra/action-commit-push@master
      #   with:
      #     github_token: "${{ secrets.GITHUB_TOKEN }}"
      #     add_timestamp: true
      #     commit_prefix: "[AUTO]"
      #     commit_message: ${{ env.version }}
      #     force: false
      #     target_branch: master

  increase-core-version:
    needs: increase-browser-version
    runs-on: linux-vm
    defaults:
      run:
        working-directory: ../../brave-core
    steps:
      - name: checkout master
        uses: actions/checkout@v3
        with:
          repository: 'nguyenphl/brave-core'
          ref: 'master'
          path: '../../brave-core'

      - name: reset working space
        run: |
          git restore *
          git reset
      
      - name: pull new source
        run: git pull origin

      - name: get current version
        run: ls ../

      - name: update version
        id: update_version
        shell: bash
        run: |
          file_path="package.json"
          version=$(jq -r '.version' $file_path)

          IFS='.' read -ra version_parts <<< "$version"
          last_part=${version_parts[2]}

          new_last_part=$((last_part+1))

          new_version="${version_parts[0]}.${version_parts[1]}.$new_last_part"
          jq --arg new_version "$new_version" '.version = $new_version' $file_path > tmp.json && mv tmp.json $file_path

          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: updated to version ${{env.new_version}}
        run: echo ${{env.new_version}}

      - name: change chromium version
        run: |
          # Read the current patch version from the patch file
          patch=$(grep "^+PATCH=" ./patches/chrome-VERSION.patch | cut -d "=" -f 2)

          # Convert the patch version to an integer
          patch=$(($patch))

          # Increment the patch version by 1
          patch=$(($patch + 1))

          # Replace the old patch version with the new one
          sed -i "s/^+PATCH=[0-9]*/+PATCH=$patch/" ./patches/chrome-VERSION.patch
        
      - name: show change
        run: git status

      # - name: change working dir
      #   run: cd ../brave-core 

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: herond-builds@herondlabs.org
          author_name: herond-builds
          message: ${{env.new_version}}
          branch: master

      # - name: commit change
      #   run: |
      #     git config user.email "herond-builds@herondlabs.com"
      #     git config user.name "herond-builds"
      #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      #     git add package.json
      #     git add ./patches/chrome-VERSION.patch
      #     git commit -m ${{env.new_version}}
      #     git push

      

  # build:
  #   strategy:
  #     # os: []
  #     # arch: []
  #     matrix:
  #       include:
  #         # - os: windows-vm
  #         #   arch: ia32
  #         # - os: windows-vm
  #         #   arch: x64
  #         - os: linux-vm
  #           arch: amd64
  #         # - os: linux-vm
  #         #   arch: arm64
  #         # - os: android-vm
  #         #   arch: arm
        
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: checkout master
  #       uses: actions/checkout@v3
  #       with:
  #         ref: 'master'

  #     - name: pull new source
  #       run: git pull

  #     - name: install deps
  #       run: npm i

  #     - name: init
  #       run: npm run init --target_arch=${{ matrix.arch }}

  #     - name: build
  #       run: npm run build Release --target_arch=${{ matrix.arch }}

  # test:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:

  # create_dist:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
