name: "Build"

# on: 
#   push:
#     branches: 
#       - main
#     paths-ignore:
#       - '**/*.md'
#       - '**/*.gitignore'
#       - '**/*.gitattributes'
  
#   workflow_dispatch:
#     branches:
#       - main
#     paths-ignore:
#       - '**/*.md'
#       - '**/*.gitignore'
#       - '**/*.gitattributes'

on: push

jobs:
  build:
    strategy:
      # os: []
      # arch: []
      matrix:
        include:
          - os: windows-vm
            arch: ia32
          - os: windows-vm
            arch: x64
          - os: linux-vm
            arch: amd64
          - os: linux-vm
            arch: arm64
          # - os: android-vm
          #   arch: arm
        
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: pull
        run: git pull

      - name: install deps
        run: npm i

      - name: init
        run: npm run init --target_arch=${{ matrix.arch }}

      - name: sync
        run: npm run sync

      - name: build
        run: npm run build Release --target_arch=${{ matrix.arch }}

  # test:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:

  # create_dist:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
