name: "Bump Version"

on: 
  workflow_dispatch:
  schedule:
    - cron: '1 15 * * *' 

jobs:
  increase-browser-version:
    runs-on: linux-vm
    steps:
      - name: checkout master
        run: |
          if [ ! -d ./brave-browser/.git ]
          then
              git clone https://nguyenphl:${{ secrets.CORE_TOKEN }}@github.com/${GITHUB_REPOSITORY}
              cd brave-browser
              git config --global --add safe.directory .
              git config --local --get remote.origin.url
              git checkout master
          else
              cd brave-browser
              git pull origin
          fi
      
      - name: Reset working space
        run: |
          git restore *
          git reset
          
      - name: Pull new source
        run: git pull

      - name: Update version
        shell: bash
        run: |
          file_path="package.json"
          version=$(jq -r '.version' $file_path)

          IFS='.' read -ra version_parts <<< "$version"
          last_part=${version_parts[2]}

          new_last_part=$((last_part+1))

          new_version="${version_parts[0]}.${version_parts[1]}.$new_last_part"
          jq --arg new_version "$new_version" '.version = $new_version' $file_path > tmp.json && mv tmp.json $file_path

          echo "new_version=$new_version" >> $GITHUB_ENV
      
      - name: Updated to version ${{env.new_version}}
        run: echo ${{env.new_version}}

      - name: Show change
        run: git status

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: herond-builds@herondlabs.org
          author_name: herond-builds
          message: ${{env.new_version}}
          branch: master

  increase-core-version:
    needs: increase-browser-version
    runs-on: linux-vm
    steps:
      - name: checkout master
        working-directory: ./src/
        run: |
          if [ ! -d ./brave/.git ]
          then
              git clone https://github.com/nguyenphl/brave-core ./brave
              cd brave
              git config --global --add safe.directory .
              git config --local --get remote.origin.url
              git checkout master
          else
              cd brave
              git pull origin
          fi

      - name: Reset working space
        working-directory: ./src/brave
        run: |
          git restore *
          git reset
      
      - name: Pull new source
        working-directory: ./src/brave
        run: git pull origin

      - name: Update version
        working-directory: ./src/brave
        shell: bash
        run: |
          file_path="package.json"
          version=$(jq -r '.version' $file_path)

          IFS='.' read -ra version_parts <<< "$version"
          last_part=${version_parts[2]}

          new_last_part=$((last_part+1))

          new_version="${version_parts[0]}.${version_parts[1]}.$new_last_part"
          jq --arg new_version "$new_version" '.version = $new_version' $file_path > tmp.json && mv tmp.json $file_path

          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Updated to version ${{env.new_version}}
        run: echo ${{env.new_version}}

      - name: Change chromium version
        working-directory: ./src/brave
        run: |
          # Read the current patch version from the patch file
          patch=$(grep "^+PATCH=" ./patches/chrome-VERSION.patch | cut -d "=" -f 2)

          # Convert the patch version to an integer
          patch=$(($patch))

          # Increment the patch version by 1
          patch=$(($patch + 1))

          # Replace the old patch version with the new one
          sed -i "s/^+PATCH=[0-9]*/+PATCH=$patch/" ./patches/chrome-VERSION.patch
        
      - name: Show change
        working-directory: ./src/brave
        run: git status

      - name: Push
        uses: actions-js/push@master
        with:
          repository: nguyenphl/brave-core
          github_token: ${{ secrets.CORE_TOKEN }}
          author_email: herond-builds@herondlabs.org
          author_name: herond-builds
          message: ${{env.new_version}}
          branch: master
          directory: ./src/brave

      - name: Tag
        run: |
          git remote set-url origin https://${{ secrets.CORE_TOKEN }}@github.com/nguyenphl/brave-core
          git tag -a v${{env.new_version}}
          git push origin master --tags

      # - name: Tag
      #   run: |
      #     git remote set-url origin https://${{ secrets.CORE_TOKEN }}@github.com/nguyenphl/brave-core
      #     git tag -a v${{env.new_version}} -m "${{env.new_version}}"
      #     git push origin v${{env.new_version}}

  
